import Header from "./Components/Header";
import Footer from "./Components/Footer";
import "./globals.css";

import { CartProvider } from "./context/cartContext.js";

export const metadata = {
  title: "MN Grocery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Header />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
